### ISSUE TITLE
Modify the display for website

### ISSUE THREAD

**Issue by B10715018** [B10715018/b10715018.github.io#4]
- [ ] modify display for home layout into 4 little table which includes all the thing that the company sells
- [ ] modify about us : clearly only to put vision and mission and history of company profile
- [ ] modify contact: add the personal phone number and add a better logo for it
- [ ] for 4 things that company sells each of the image can be click and turn into one page
- [x] #5
- [ ] for the ` extrusion` would show all the extrusiom
- [ ] for the `caroseri` will show all type of caroseri
- [ ] for the `sheet` will show all type of caroseri
